### PR TITLE
Add the new parameter for filter

### PR DESCRIPTION
**Pull request by gergo85**
Now possible to change the mediathumb folder name.

### CODE REVIEW

**Comment by bastihilger** [comment]
Thank you for your contribution. I hesitate to add another parameter, though. Wouldn't it be enough to just add a "folder" key in the config file which is set to "_mediathumbs" but could be changed by the user, like so?

```
return [

    /* 
    Change the folder for the thumbnails inside your media directory.
    Is set to '_mediathumbs' originally, but can be any folder or
    subfolder like 'your/custom/mediathumbs/folder'
    */

    'folder' => '_mediathumbs',

    // Set the defaults for creating mediathumbs

    'default' => [
        'mode' => 'auto',
        'size' => 200,
        'quality' => 90,
    ]
];

```

 The files are generated automatically if they don't exist, so one could even change the folder name after the plugin is already in use. Would that be OK for your?

**Comment by bastihilger** [comment]
Or do you need multiple different folder names inside one project? Then of course only your solution makes sense.

**Comment by gergo85** [comment]
Your solution is easier. And I would like to change the folder name so I don't need multiple folders.

**Comment by bastihilger** [comment]
Thanks again - I changed the plugin with an option to change the folder inside the config file. The plugin will be updated in an minute.

**Comment by gergo85** [comment]
Thank you for your fast work!

**Pull request closed without merging**
